# Site settings
name: Bocheng Zhong
title: Bocheng Zhong | Technical Developer & Researcher
description: Technical developer and researcher with hands-on experience in hardware, audio, sensing, prototyping, and product-oriented system building
url: https://bochengzhong.github.io
baseurl: ''
email: zhongbc87@qq.com
cover: https://bochengzhong.github.io/img/og.png
logo: https://bochengzhong.github.io/img/emojis/technologist.png
resume: ''
social:
  - title: email
    url: mailto:zhongbc87@qq.com
  - title: linkedin
    url: https://www.linkedin.com/in/bocheng-zhong-742283355
  - title: github
    url: https://github.com/bochengzhong

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
